# Generated by Django 5.1.1 on 2024-10-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='horario',
            field=models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('C', 'Completo'), ('O', 'Otros')], default='M', max_length=1),
        ),
    ]
