# Generated by Django 5.1.1 on 2024-10-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_registroactividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroactividad',
            name='turno',
            field=models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('C', 'Completo')], default='M', max_length=1),
        ),
    ]
