# Generated by Django 5.1.1 on 2024-11-06 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_registroactividad_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='jefe_mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jefe_mesa', to='gestion.empleado'),
        ),
    ]
